### ISSUE TITLE
Swift Implementation of 'Segue accessors' duplicates enum definition

### ISSUE THREAD

**Issue by robfeldmann** [Dynamit/referee#1]
I'm using Swift. If I have two+ segues identified, the generated Swift output becomes:

    /// Segue accessors.
    enum Segues: String {
        case FirstSegue = "FirstSegue"
    }
    /// Segue accessors.
    enum Segues: String {
        case SecondSegue = "SecondSegue"
    }

This leads to an `invalid redeclaration of 'Segues'` build error.

Need to figure out why the templating system is allowing this for segues.

Note that I initially thought this was due to new "reference" segues in Xcode 7+ but it seems to be the case for all identified segues. I did not attempt the same thing in Objective-C yet.

**Comment by cfdrake** [comment]
Hoping to take a look at this in the next few days provided I get some free time.

**Comment by cfdrake** [comment]
It looks like we had a bug in the Swift template while iterating across `enum` types. [Fixed in latest commit.](https://github.com/Dynamit/referee/commit/a3ee5161a06e68a1097827cd4d899698342bd6d8#diff-bbcfcb75f8360981374d49874348ffa2L34)

**Comment by cfdrake** [comment]
I'd like to get this pushed out in a release ASAP - I've got one small, personally uncovered `enum` bug that I'd like to include in this release bundle as well.

**Comment by cfdrake** [comment]
Verified IRL 😎

Creating a release with these two `enum` issues fixed.
