### ISSUE TITLE
View controllers should be returned as their own type

### ISSUE THREAD

**Issue by cfdrake** [Dynamit/referee#2]
Instead of returning generic `UIViewController`, the appropriate subclass (if provided in the Storyboard) should be returned.

*Sanity check:* A `guard` statement should test this cast and `fatalError` if the cast fails.

**Comment by cfdrake** [comment]
(As of right now, this is a WIP stash I'm currently hacking on)

**Comment by cfdrake** [comment]
I've fixed this in an unreleased version of the code.

This will probably result in a major revision version-bump, given the output of the tool now differs from the past (despite that it will still compile).

**Comment by rafaelnobrepd** [comment]
In Objective-C, I realize the generated Resources class does not know about the specific view controller types (i.e. no import statements or forward declarations are generated). Is there a workaround for this ? Should this tool be used at all as of right now ? Its the only one supporting Objective-C as far as I have researched.
